import{a as w,S as q,i as c}from"./assets/vendor-BjRz3xa9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const S="https://pixabay.com/api/",v="49651388-bf829c1018596f8ebf90706c1";async function u(i,o=1){return(await w.get(S,{params:{key:v,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}let l;const f=document.querySelector(".gallery");function m(i){const o=i.map(({webformatURL:r,largeImageURL:s,tags:e,likes:t,views:a,comments:b,downloads:L})=>`
            <a class="gallery__item" href="${s}">
             <img class="gallery__image" src="${r}" alt="${e}" />
               <div class="info">
              <p class="info-item"><b>Likes:</b> ${t}</p>
              <p class="info-item"><b>Views:</b> ${a}</p>
              <p class="info-item"><b>Comments:</b> ${b}</p>
              <p class="info-item"><b>Downloads:</b> ${L}</p>
            </div>
        </a>`).join("");f.insertAdjacentHTML("beforeend",o),l?l.refresh():l=new q(".gallery a",{captionsData:"alt",captionDelay:250})}function _(){return f.innerHTML=""}function p(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}function P(){document.querySelector(".load-more").classList.remove("load-more-hidden")}function h(){document.querySelector(".load-more").classList.add("load-more-hidden")}const E=document.querySelector(".form"),M=document.querySelector(".load-more");let d="",n=1;const y=15;E.addEventListener("submit",async i=>{i.preventDefault();const o=i.currentTarget.elements.searchQuery.value.trim();if(!o){c.warning({title:"Attention",message:"Input yuor request!",position:"topRight"});return}try{p(),h(),_(),d=o,n=1;const r=await u(d,n);if(r.hits.length===0){c.info({title:"There is nothing was found",message:"Try another request",position:"topRight"});return}m(r.hits);const s=Math.ceil(r.totalHits/y);n<s&&P()}catch{c.error({title:"Error",message:"Something went wrong!",position:"topRight"})}finally{g()}});M.addEventListener("click",async()=>{n+=1;try{p();const i=await u(d,n);m(i.hits);const o=Math.ceil(i.totalHits/y);n>=o&&(h(),c.info({title:"End of collection",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const r=document.querySelector(".gallery .gallery__item");if(r){const{height:s}=r.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}}catch{c.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{g()}});
//# sourceMappingURL=index.js.map
