import{a as w,S as q,i as l}from"./assets/vendor-BjRz3xa9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const S="https://pixabay.com/api/",v="49651388-bf829c1018596f8ebf90706c1";async function m(i,r=1){return(await w.get(S,{params:{key:v,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}let d;const p=document.querySelector(".gallery");function h(i){const r=i.map(({webformatURL:t,largeImageURL:s,tags:e,likes:o,views:a,comments:b,downloads:L})=>`
            <a class="gallery__item" href="${s}">
             <img class="gallery__image" src="${t}" alt="${e}" />
               <div class="info">
              <p class="info-item"><b>Likes:</b> ${o}</p>
              <p class="info-item"><b>Views:</b> ${a}</p>
              <p class="info-item"><b>Comments:</b> ${b}</p>
              <p class="info-item"><b>Downloads:</b> ${L}</p>
            </div>
        </a>`).join("");p.insertAdjacentHTML("beforeend",r),d?d.refresh():d=new q(".gallery a",{captionsData:"alt",captionDelay:250})}function _(){return p.innerHTML=""}function g(){document.querySelector(".loader").classList.remove("hidden")}function y(){document.querySelector(".loader").classList.add("hidden")}function P(){document.querySelector(".load-more").classList.remove("load-more-hidden")}function c(){document.querySelector(".load-more").classList.add("load-more-hidden")}const E=document.querySelector(".form"),M=document.querySelector(".load-more");c();let u="",n=1;const f=15;E.addEventListener("submit",async i=>{i.preventDefault();const r=i.currentTarget.elements.searchQuery.value.trim();if(!r){l.warning({title:"Attention",message:"Input yuor request!",position:"topRight"});return}try{g(),c(),_(),u=r,n=1;const t=await m(u,n);if(t.hits.length===0){l.info({title:"There is nothing was found",message:"Try another request",position:"topRight"}),c();return}h(t.hits);const s=Math.ceil(t.totalHits/f);t.hits.length<f||n>=s?c():P()}catch{l.error({title:"Error",message:"Something went wrong!",position:"topRight"})}finally{y()}});M.addEventListener("click",async()=>{n+=1;try{g();const i=await m(u,n);h(i.hits);const r=Math.ceil(i.totalHits/f);n>=r&&(c(),l.info({title:"End of collection",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const t=document.querySelector(".gallery .gallery__item");if(t){const{height:s}=t.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}}catch{l.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{y()}});
//# sourceMappingURL=index.js.map
